# alorenzetti 20211111

# description ####

# this script will analyze 
# known Quillaja saponaria
# bAS and p450 involved in 
# quillaic acid biosynthesis
# and recover homologs in 
# Quillaja brasiliensis

# getting started ####
# declaring sequences included in patent AU2018386458A1
# https://patentimages.storage.googleapis.com/2f/b6/24/8adc75c398accd/AU2018386458A1.pdf
qsap = list()

# bAS
# getting nt sequence
qsap$bAS$nt = DNAStringSet(x = "ATGTGGAGGCTGAAGATAGCAGAAGGTGGTTCCGATCCATATCTGTTCAGCACAAACAACTTCGTGGGTCGCCAGACATGGGAGTTCGAACCGGAGGCCGGCACACCTGAGGAGCGAGCAGAGGTCGAAGCTGCCCGCCAAAACTTTTACAACAACCGTTACCAGGTCAAGCCCTGTGACGACCTCCTTTGGAGATATCAGTTCCTGAGAGAGAAGAATTTCAAACAAACAATACCGCCTGTCAAGGTTGAAGATGGCCAAGAAATTACTTATGAGATGGCCACAACCTCAATGCAGAGGGCGGCCCGTCACCTATCAGCCTTGCAGGCCAGCGATGGCCATTGGCCAGCTCAAATTGCTGGCCCCTTGTTCTTCATGCCACCCTTGGTCTTTTGTGTGTACATTACTGGGCATCTTAATACAGTATTCCCATCTGAACATCGCAAAGAAATCCTTCGTTACATGTACTATCACCAGAACGAAGATGGTGGGTGGGGACTGCACATAGAGGGTCACAGCACCATGTTTTGCACAGCACTCAACTACATTTGTATGCGTATCCTTGGGGAAGGACCAGAGGGGGGTCAAGACAATGCTTGTGCCAGAGCACGAATGTGGATTCTTGATCATGGTGGTGTAACACATATTCCATCTTGGGGAAAGACCTGGCTTTCGATACTTGGTCTATTTGAGTGGTCTGGAAGCAATCCAATGCCTCCAGAGTTTTGGATCCTTCCTTCATTTCTTCCTATGCATCCAGCAAAAATGTGGTGCTATTGCCGGATGGTTTACATGCCCATGTCTTATTTATATGGGAAAAGGTTTGTTGGCCCAATCACGCCTCTCATTGTTCAGTTAAGAGAGGAAATACACACTCAAAATTACCATGAAATCAACTGGAAGTCAGTCCGCCATCTATGTGCAAAGGAGGATATCTACTATCCCCATCCACTCATCCAAGATTTGATTTGGGACAGTTTGTACATACTAACGGAGCCTCTTCTCACTCGCTGGCCCTTGAACAAGTTGGTGCGGGAGAGGGCTCTCCAAGTAACAATGAAGCATATCCACTATGAAGATGAAAATAGTCGATACATAACCATTGGATGTGTGGAAAAGGTGTTATGTATGCTTGCTTGTTGGGTTGATGATCCAAATGGAGATGCTTTCAAGAAGCACCTTGCTCGAGTCCCAGATTACGTATGGGTCTCTGAAGATGGAATTACTATGCAGAGTTTTGGTAGTCAAGAATGGGATGCTGGCTTTGCCGTCCAGGCTCTGCTTGCTTCTAATCTTACCGAGGAACTTGGCCCTGCTCTTGCCAAAGGACATGACTTCATAAAGCAATCTCAGGTTAAGGACAATCCTTCAGGTGACTTCAAAAGCATGTATCGTCACATTTCTAGAGGATCATGGACCTTCTCTGACCAAGATCATGGATGGCAAGTTTCTGATTGCACTGCAGAAGGTCTGAAGTGTTGCCTGCTTTTGTCGATGTTGCCACCAGAAATTGTTGGTGAAAAAATGGAACCACAAAGGCTATTTGATTCTGTCAATGTGCTGCTCTCTCTACAGAGCAAAAAAGGTGGTTTAGCTGCCTGGGAGCCAGCAGGGGCGCAAGATTGGTTGGAATTACTCAATCCCACAGAATTTTTTGCGGACATTGTCGTTGAGCATGAATATGTTGAATGTACTGGATCAGCAATTCAGGCATTAGTTTTGTTCAAGAAGCTGTATCCGGGGCACAGGAAAAAAGAGATTGACAGTTTCATTACAAATGCTGTCCGGTTCCTTGAGAATACACAAACGGCAGATGGCTCTTGGTATGGAAACTGGGGAGTTTGCTTCACCTATGGTTGTTGGTTCGCACTGGGAGGGCTAGCAGCAGCTGGCAAGACTTACAACAACTGTCCTGCAATACGCAAAGCTGTTAATTTCCTACTTACAACACAAAGAGAAGACGGTGGTTGGGGAGAAAGCTATCTTTCAAGCCCAAAAAAGATATATGTACCCCTGGAAGGAAGCCGATCAAATGTGGTACATACTGCATGGGCTATGATGGGTCTAATTCATGCTGGGCAGGCTGAAAGAGACTCAACTCCTCTTCATCGTGCAGCAAAGTTGATCATCAATTATCAACTAGAAAATGGCGATTGGCCGCAACAGGAAATCACTGGAGTATTCATGAAAAACTGCATGTTACATTACCCTATGTACAGAAACATCTACCCAATGTGGGCTCTTGCAGAATACCGGAGGCGGGTTCCATTGCCTTAA"
)
names(qsap$bAS$nt) = "QsbAS|OQHZ-2074321|Qsap|beta-amyrin synthase"

# getting aa sequence
qsap$bAS$aa = AAStringSet(x = "MWRLKIAEGGSDPYLFSTNNFVGRQTWEFEPEAGTPEERAEVEAARQNFYNNRYQVKPCDDLLWRYQFLREKNFKQTIPPVKVEDGQEITYEMATTSMQRAARHLSALQASDGHWPAQIAGPLFFMPPLVFCVYITGHLNTVFPSEHRKEILRYMYYHQNEDGGWGLHIEGHSTMFCTALNYICMRILGEGPEGGQDNACARARMWILDHGGVTHIPSWGKTWLSILGLFEWSGSNPMPPEFWILPSFLPMHPAKMWCYCRMVYMPMSYLYGKRFVGPITPLIVQLREEIHTQNYHEINWKSVRHLCAKEDIYYPHPLIQDLIWDSLYILTEPLLTRWPLNKLVRERALQVTMKHIHYEDENSRYITIGCVEKVLCMLACWVDDPNGDAFKKHLARVPDYVWVSEDGITMQSFGSQEWDAGFAVQALLASNLTEELGPALAKGHDFIKQSQVKDNPSGDFKSMYRHISRGSWTFSDQDHGWQVSDCTAEGLKCCLLLSMLPPEIVGEKMEPQRLFDSVNVLLSLQSKKGGLAAWEPAGAQDWLELLNPTEFFADIVVEHEYVECTGSAIQALVLFKKLYPGHRKKEIDSFITNAVRFLENTQTADGSWYGNWGVCFTYGCWFALGGLAAAGKTYNNCPAIRKAVNFLLTTQREDGGWGESYLSSPKKIYVPLEGSRSNVVHTAWAMMGLIHAGQAERDSTPLHRAAKLIINYQLENGDWPQQEITGVFMKNCMLHYPMYRNIYPMWALAEYRRRVPLP*"
)
names(qsap$bAS$aa) = "QsbAS|OQHZ-2074321|Qsap|beta-amyrin synthase"

# P450
# names
nms = c("QsCYP716_2073932|OQHZ-2073932|Qsap|C-28 oxidase",
        "QsCYP716_2012090|OQHZ-2012090|Qsap|C-16a oxidase",
        "QsCYP714_c36368|OQHZ-2018687|Qsap|C-23 oxidase candidate"
)

# getting nt sequence
seqsnt = c("ATGGAGCACTTGTATCTCTCCCTTGTGCTCCTGTTTGTTTCCTCAATCTCCCTCTCCCTCTTCTTCCTGTTCTACAAACACAAATCTATGTTCACCGGGGCCAACCTACCACCTGGTAAAATCGGTTACCCATTGATCGGAGAGAGCTTGGAGTTCTTGTCCACGGGATGGAAGGGCCACCCGGAGAAATTCATCTTCGATCGCATGAGCAAGTACTCATCCCAAATCTTCAAGACCTCGATTTTAGGGGAACCAACGGCGGTGTTCCCGGGAGCCGTATGCAACAAGTTCCTCTTCTCCAACGAGAACAAGCTGGTGAATGCATGGTGGCCTGCCTCCGTGGACAAGATCTTTCCTTCCTCACTCCAGACATCCTCCAAAGAAGAGGCCAAGAAGATGAGGAAGTTGCTTCCTCAGTTTCTCAAGCCCGAAGCTCTGCACCGCTACATTGGTATTATGGATTCTATTGCCCAGAGACACTTTGCCGATAGCTGGGAAAACAAAAACCAAGTCATTGTCTTTCCTCTAGCAAAGAGGTATACTTTCTGGCTGGCTTGCCGTTTGTTCATTAGCGTCGAGGATCCGACCCACGTATCCAGATTTGCTGACCCGTTCCAACTTTTGGCCGCCGGAATCATATCAATCCCAATCGACTTGCCAGGGACACCGTTCCGCAAGGCAATCAATGCGTCCCAGTTCATCAGGAAGGAATTGTTGGCCATCATCAGGCAGAGAAAGATCGATTTGGGTGAAGGGAAGGCATCTCCGACGCAGGACATACTGTCTCACATGTTGCTCACATGCGACGAGAACGGACAATACATGAATGAATTGGACATTGCCGACAAGATTCTTGGCTTGTTGGTCGGCGGACATGACACTGCCAGTGCCGCTTGCACTTTCATTGTCAAGTTCCTCGCTGAGCTTCCCCACATTTATGAACAAGTCTACAAGGAGCAAATGGAGATTGCAAAATCAAAAGTGCCAGGAGAGTTGTTGAATTGGGAGGACATCCAAAAGATGAAATATTCGTGGAACGTAGCTTGTGAAGTGATGAGACTTGCCCCTCCACTCCAAGGAGCTTTCAGGGAAGCCATTACTGACTTCGTCTTCAACGGTTTCTCCATTCCAAAAGGCTGGAAGTTGTACTGGAGCGCAAATTCCACCCACAAAAGTCCGGATTATTTCCCTGAGCCCGACAAGTTCGACCCAACTAGATTCGAAGGAAATGGACCTGCGCCTTACACCTTTGTTCCATTTGGGGGAGGACCCAGGATGTGCCCGGGCAAAGAGTATGCCCGATTGGAAATACTTGTGTTCATGCATAACTTGGTGAAGAGGTTCAAGTGGGAGAAATTGGTTCCTGATGAAAAGATTGTGGTTGATCCAATGCCCATTCCAGCAAAGGGTCTTCCTGTTCGCCTTTATCCTCACAAAGCTTGA",
           "ATGGATCCTTTCTTCATTTTTGGCTTACTTCTCTTGGCTCTCTTTCTCTCTGTTTCTTTTCTTCTCTACCTTTCCCGTAGAGCCTATGCTTCTCTCCCCAACCCTCCGCCGGGGAAGCTCGGCTTCCCCGTCGTCGGCGAGAGTCTCGAATTTCTCTCCACCCGACGCAAAGGTGTTCCTGAGAAATTCGTCTTCGACAGAATGGCCAAATACTGTCGGGATGTCTTTAAGACATCAATATTGGGAGCAACCACCGCCGTCATGTGCGGCACCGCCGGTAACAAATTCTTGTTCTCCAACGAGAAAAAACACGTCACTGGTTGGTGGCCGAAATCTGTAGAGCTGATTTTCCCAACCTCACTTGAGAAATCATCCAACGAAGAATCCATCATGATGAAACAATTCCTTCCCAACTTCTTGAAACCAGAACCTTTGCAGAAGTACATACCCGTTATGGACATAATTACCCAAAGACACTTCAATACAAGCTGGGAAGGACGCAACGTGGTCAAAGTGTTTCCTACGGCTGCCGAATTCACCACGTTGCTGGCTTGTCGGGTATTCCTCAGTGTTGAGGATCCCATTGAAGTAGCCAAGATTTCAGAGCCATTTGAAATCTTAGCTGCTGGGTTTCTTTCAATACCCATAAATCTTCCGGGTACCAAATTAAATAAAGCGGTTAAGGCAGCGGATCAGATTAGAGACGCAATTGTACAGATTTTGAAACGGAGAAGGGTTGAAATTGCGGAGAATAAAGCAAATGGAATGCAAGATATAGCGTCCATGTTGTTGACGACACCAACTAATGCTGGGTTTTATATGACCGAGGCTCACATTTCTGAGAAAATTTTGGGTATGATTGTTGGTGGCCGTGATACTGCTAGTACTGTTATCACCTTCATCATCAAGTATTTGGCAGAGAATCCTGAAATTTATAATAAGGTCTATGAGGAGCAAATGGAAGTGGTAAAGTCAAAGAAACCAGGTGAGTTGCTGAACTGGGAAGATGTGCAGAAAATGAAGTACTCTTGGTGCGTAGCATGTGAAGCTATGCGACTTGCTCCTCCTGTTCAAGGTGGTTTCAAGGTGGCCATTAATGACTTTGTGTATTCTGGGTTCAACATTCGCAAGGGTTGGAAGTTATATTGGAGTGCCATTGCAACACACATGAATCCAGAATATTTCCCAGAACCTGAGAAATTCAACCCCTCAAGGTTTGAAGGGAAGGGACCAGTACCTTACAGCTTCGTACCCTTCGGAGGCGGACCTCGGATGTGTCCCGGGAAAGAGTATTCCCGGCTGGAAACACTTGTTTTCATGCATCATTTGGTGACGAGGTACAATTGGGAGAAAGTGTATCCCACAGAGAAGATAACAGTGGATCCAATGCCATTCCCTGTCAACGGCCTCCCCATTCGCCTTATTCCTCACAAGCACCAATGA",
           "ATGTGGTTCACAGTAGGATTGGTCTTGGTTTTCGCCCTATTCATACGTCTCTACAGCAGTCTGTGGTTGAAGCCTCGTGCAACTCGGATTAAGCTTAGCAATCAAGGAATTAAAGGTCCAAAACCAGCATTTCTTCTGGGTAATGTTGCAGAGATGAGAAGATTTCAATCTAAGCTTCCAAAATCTGAACTCAAACAAGGCCAAGTTTCTCATGATTGGGCTTCTAAATCTCTGTTTCCATTTTTCAGTCTTTGGTCCCAGAAATACGGAAATACGTTCGTGTTCTCATTGGGGAACATACAGGTGCTCTATGTTTCTGATCATGAGTTGGTGAAAGAAATTAATCAGAATACCTCTTTAGATTTGGGCAAACCCAAGTACCTGCAGAAGGAGCGTGGCCCTTTGCTGGGACAAGGTATTTTGACCTCCAATGGACAGCTTTGGGCGTACCAGAGAAAAATCATGACTCCTGAACTCTACAAGGAGAAAATCAAGGGCATGTGCGAGTTGATGGTGGAATCTGTAGCTTGGTTGGTTGAGGAATGGGGAACGAAGATCCAAGCTGAGGGTGGGGCAGCAGACATTAGAATAGACGAGGATCTTAGAAGCTTCTCTGGTGATGTAATTTCAAAAGCTTGTTTTGGGAGCTGCTATGCCGGAGGGAGGGAAATCTTTCTTAGGCTCAGAGCTCTTCAACACCAAATTGCTTCCAAAGCCTTACTCATGGGCTTCCCTGGATTAAAGTACCTGCCCATTAAGAGCAACAGAGAGATATGGAGATTGGAGAAGGAGATCTTCCAGCTGATTATGAAGCTGGCTGAAGATAGAAAAAAAGAACAACATGAGAGAGACCTATTACAGATTATAATTGAGGGAGCTAAAAGTAGTGATCTGAGTTCGGAAGCAATGGCAAAATTCATTGTGGACAACTGCAAGAATGTCTACTTGGCTGGCCATGAAACTACTGCAATGTCTGCTGGTTGGACTTTGCTTCTCTTGGCTAATCATCCTGAGTGGCAAGCCCGTGTCCGTGATGAGATTTTACAAGTCACCGAGGGCCGCAATCCTGATTTTGACATGCTGCACAAGATGAAACTGTTAACAATGGTAATTCAGGAGGCACTGCGACTCTACCCAACAGTCATATTCATGTCAAGAGAAGCATTGGAAGATATTAATGTTGGAAACATCCAAGTTCCAAAAGGTGTTAACATATGGATACCTGTGGTAAATCTTCAAAGGGACACAACGGTATGGGGTGCAGACGCAAACGAGTTTAATCCTGAAAGGTTTGCCAATGGAGTTAACAATTCATGCAAGGTTCCACAACTTTACCTACCATTTGGAGCTGGACCTCGCATTTGTCCTGGAATTAATCTGGCCATGACTGAGATCAAGATACTTCTGTGTATCCTGCTCACCAAGTTTTCGTTTTCAGTTTCACCCAACTATCGCCACTCACCGGTGTTTAAATTGGTGCTTGAGCCTGAAAATGGAATCAATGTCATCATGAAGAAGCTCTAA"
)

# getting aa sequence
seqsaa = c("MEHLYLSLVLLFVSSISLSLFFLFYKHKSMFTGANLPPGKIGYPLIGESLEFLSTGWKGHPEKFIFDRMSKYSSQIFKTSILGEPTAVFPGAVCNKFLFSNENKLVNAWWPASVDKIFPSSLQTSSKEEAKKMRKLLPQFLKPEALHRYIGIMDSIAQRHFADSWENKNQVIVFPLAKRYTFWLACRLFISVEDPTHVSRFADPFQLLAAGIISIPIDLPGTPFRKAINASQFIRKELLAIIRQRKIDLGEGKASPTQDILSHMLLTCDENGQYMNELDIADKILGLLVGGHDTASAACTFIVKFLAELPHIYEQVYKEQMEIAKSKVPGELLNWEDIQKMKYSWNVACEVMRLAPPLQGAFREAITDFVFNGFSIPKGWKLYWSANSTHKSPDYFPEPDKFDPTRFEGNGPAPYTFVPFGGGPRMCPGKEYARLEILVFMHNLVKRFKWEKLVPDEKIVVDPMPIPAKGLPVRLYPHKA*",
           "MDPFFIFGLLLLALFLSVSFLLYLSRRAYASLPNPPPGKLGFPVVGESLEFLSTRRKGVPEKFVFDRMAKYCRDVFKTSILGATTAVMCGTAGNKFLFSNEKKHVTGWWPKSVELIFPTSLEKSSNEESIMMKQFLPNFLKPEPLQKYIPVMDIITQRHFNTSWEGRNVVKVFPTAAEFTTLLACRVFLSVEDPIEVAKISEPFEILAAGFLSIPINLPGTKLNKAVKAADQIRDAIVQILKRRRVEIAENKANGMQDIASMLLTTPTNAGFYMTEAHISEKILGMIVGGRDTASTVITFIIKYLAENPEIYNKVYEEQMEVVKSKKPGELLNWEDVQKMKYSWCVACEAMRLAPPVQGGFKVAINDFVYSGFNIRKGWKLYWSAIATHMNPEYFPEPEKFNPSRFEGKGPVPYSFVPFGGGPRMCPGKEYSRLETLVFMHHLVTRYNWEKVYPTEKITVDPMPFPVNGLPIRLIPHKHQ*",
           "MWFTVGLVLVFALFIRLYSSLWLKPRATRIKLSNQGIKGPKPAFLLGNVAEMRRFQSKLPKSELKQGQVSHDWASKSLFPFFSLWSQKYGNTFVFSLGNIQVLYVSDHELVKEINQNTSLDLGKPKYLQKERGPLLGQGILTSNGQLWAYQRKIMTPELYKEKIKGMCELMVESVAWLVEEWGTKIQAEGGAADIRIDEDLRSFSGDVISKACFGSCYAGGREIFLRLRALQHQIASKALLMGFPGLKYLPIKSNREIWRLEKEIFQLIMKLAEDRKKEQHERDLLQIIIEGAKSSDLSSEAMAKFIVDNCKNVYLAGHETTAMSAGWTLLLLANHPEWQARVRDEILQVTEGRNPDFDMLHKMKLLTMVIQEALRLYPTVIFMSREALEDINVGNIQVPKGVNIWIPVVNLQRDTTVWGADANEFNPERFANGVNNSCKVPQLYLPFGAGPRICPGINLAMTEIKILLCILLTKFSFSVSPNYRHSPVFKLVLEPENGINVIMKKL*"
)

# assigning
qsap$p450$nt = DNAStringSet(x = seqsnt)
names(qsap$p450$nt) = nms

qsap$p450$aa = AAStringSet(x = seqsaa)
names(qsap$p450$aa) = nms

# getting qbra P450 sequences
qbra = list()

# nt
qbra$p450$nt =DNAStringSet(x = codan$full[codan$full$transcript_id %in% tps_p450$p450$transcript_id,] %>% 
                             pull(codan_nt))
names(qbra$p450$nt) = paste0(names(qbra$p450$nt), "|", names(qbra$p450$nt), "|", "Qbra", "|", "Contains PF00067 P450")

# aa
qbra$p450$aa = AAStringSet(x = codan$full[codan$full$transcript_id %in% tps_p450$p450$transcript_id,] %>% 
                             pull(codan_aa))
names(qbra$p450$aa) = paste0(names(qbra$p450$aa), "|", names(qbra$p450$aa), "|", "Qbra", "|", "Contains PF00067 P450")

# writing fasta files
# bAS
# nt
writeXStringSet(x = qsap$bAS$nt,
                filepath = "results/qsap_bAS.fna",
                format = "fasta")

# aa
writeXStringSet(x = qsap$bAS$aa,
                filepath = "results/qsap_bAS.faa",
                format = "fasta")

# p450
# nt
writeXStringSet(x = qsap$p450$nt,
                filepath = "results/qsap_p450.fna",
                format = "fasta")

writeXStringSet(x = qbra$p450$nt,
                filepath = "results/qbra_p450.fna",
                format = "fasta")

# aa
writeXStringSet(x = qsap$p450$aa,
                filepath = "results/qsap_p450.faa",
                format = "fasta")

writeXStringSet(x = qbra$p450$aa,
                filepath = "results/qbra_p450.faa",
                format = "fasta")

# performing reciprocal best blast hit
# between protein sequences to find
# equivalent P450 from Qsap in Qbra
rbbh = list()
rbbh$p450 = blast_rec(query_file = "results/qbra_p450.faa",
                      subject_file = "results/qsap_p450.faa",
                      format = "fasta",
                      seq_type = "protein",
                      blast_algorithm = "blastp")

# after performing RBBH it seems that
# C-28 oxidase matches PB.19715.1
# C-16a oxidase matches PB.20962.1
# C-23 oxidase matches PB.19022.1

# doing the same for bAS
# but searching bAS in coding sequences
# predicted by CodAn
rbbh$bAS = blast_rec(query_file = "../isoquill/codan/codan_full_pred/PEP_sequences.fa",
                     subject_file = "results/qsap_bAS.faa",
                     format = "fasta",
                     seq_type = "protein",
                     blast_algorithm = "blastp")

# after performing RBBH it seems that
# bAS matches PB.10364.1

# # setting up filter
# c28c16ac23 = list()
# 
# fil = c("PB.19715.1", "PB.19715.2", "PB.19715.4",
#         "PB.20962.1", "PB.20962.3", "PB.20962.2",
#         "PB.19022.1", "PB.19022.2")
# 
# c28c16ac23$aa = (qbra$p450$aa)
# names(c28c16ac23$aa) = str_replace(names(c28c16ac23$aa), "\\|.*$", "")
# c28c16ac23$aa = c28c16ac23$aa[names(c28c16ac23$aa) %in% fil]
# 
# writeXStringSet(x = c(qsap$p450$aa, c28c16ac23$aa),
#                 format = "fasta")
# 
# c28c16ac23$nt = (qbra$p450$nt)
# names(c28c16ac23$nt) = str_replace(names(c28c16ac23$nt), "\\|.*$", "")
# c28c16ac23$nt = c28c16ac23$nt[names(c28c16ac23$nt) %in% fil]
# 
# writeXStringSet(x = c(qsap$p450$nt, c28c16ac23$nt),
#                 filepath = "results/p450_c28c16ac23.fna",
#                 format = "fasta")
# 
# # writing qbra transcripts
# txtmp = transcriptome
# names(txtmp) = str_replace(names(txtmp), "\\|.*", "")
# 
# txtmp = txtmp[names(txtmp) %in% fil]
# 
# writeXStringSet(x = txtmp,
#                 filepath = "results/p450_c28c16ac23_fulltranscripts.fna",
#                 format = "fasta")
# 
# # another round of MAFFT and clustering using a NJ approach
# # revealed that
# # C-28 oxidase and PB.19715.1 are identical at protein level except for the first 29 residues
# # the three PB.19715 1,2,4 isoforms are identifcal regarding the predicted protein
# # C-16a oxidase and PB.20962.1 are very similar at protein level except for the first 67 residues and 1 mismatch I->F
# # the other isoforms lack 2,3 lacks the N-terminal region, present mismatches, and possibly skip one exon
# # C-23 oxidase and PB.19022.1 are almost identical at the protein level, showing only two mismatches: I->V and L->F
