# alorenzetti 20211123

# description ####
# this script will take the abundance
# matrix generated by salmon
# and find potential reference genes
# for RT-qPCR

# getting started ####
# copying quant TPM obj
# collapsed by gene
abund = list()

abund$M = quant$abundance
abund$tib = quant$abundance %>% 
  as_tibble(rownames = "gene_id")

colnames(abund$M) = colData$sample
colnames(abund$tib) = c("gene_id", colData$sample)

# filtering out rows with at least one
# sample displaying TPM == 0
abund$tib = abund$tib %>%
  mutate(across(.cols = where(is.numeric),
                .fns = ~ case_when(.x == 0 ~ NA_real_,
                                   TRUE ~ .x))) %>% 
  drop_na() %>% 
  rowwise() %>% 
  mutate(cc_lag = mean(C1, C2, C3),
         cc_log = mean(C4b, C5b, C6b),
         cc_sta = mean(C7, C8, C9),
         leaf_reg = mean(F1, F2b, F3),
         leaf_uv = mean(F4, F5, F7)) %>% 
  dplyr::select(gene_id,
                cc_lag, cc_log, cc_sta,
                leaf_reg, leaf_uv) %>% 
  ungroup() %>% 
  mutate(across(.cols = where(is.numeric),
                .fns = ~ log2(.x))) %>% 
  rowwise() %>% 
  mutate(m = mean(c_across(where(is.numeric))),
         sd = sd(c_across(where(is.numeric))),
         cv = sd/m) %>% 
  ungroup() %>% 
  mutate(across(.cols = cc_lag:leaf_uv,
                .fns = ~ abs(.x - m),
                .names = "{col}_absRes"))
  
# filtering tibble
# to include only genes
# with mean(log2(tpm)) >= 5
# with sd(log2(tpm)) < 1
# with residual < 2
abund$tibFiltered = abund$tib %>%
  filter(
    (
      m >= 5
    ) &
      
      (
        sd < 0.5
      ) &
      
      (
        cc_lag_absRes < 2 &
          cc_log_absRes < 2 &
          cc_sta_absRes < 2 &
          leaf_reg_absRes < 2 &
          leaf_uv_absRes < 2
      )
  ) %>% 
  arrange(cv)
  
# getting the final table with
# functional categories
rtqpcrGenes = abund$tibFiltered %>% 
  dplyr::select(gene_id,
                m,
                sd,
                cv) %>% 
  left_join(x = .,
            y = funcatSeq %>% 
              filter(codan_status == "Full Length") %>% 
              group_by(gene_id) %>% 
              summarise(across(.cols = everything(),
                               .fns = ~ c(.x)[1])),
            by = "gene_id") %>% 
  dplyr::select(gene_id,
                m,
                sd,
                cv,
                gf_id,
                interpro_id,
                interpro_description,
                codan_nt)

# writing final table
write.xlsx(x = rtqpcrGenes,
           file = "results/rtqpcr_genes.xlsx",
           overwrite = T)
